### ISSUE TITLE
How can i test the model ??

### ISSUE THREAD

**Issue by devendraswamy** [kentaroy47/ObjectDetection.Pytorch#1]
Where is the testing code and did I train this model with my own dataset or coco dataset ??  if that is possible please tell me how to do that ??

**Comment by kentaroy47** [comment]
hey @devendraswamy 

eval.ipynb is the testing codes.

You can make a VOC-like data format to train with your own model.
You can do labeling with tools. I highly recommend Labelme, which is easy to use.

https://github.com/wkentaro/labelme

you can directly output VOC-like dataset from your labeled results.

look at the example below.

https://github.com/kentaroy47/labelme-voc-format/tree/master/examples

coco format is quite complex and do not support that right now..
